config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.order(:completed, created_at: :desc)
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create!(task_params)
    redirect_to root_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update!(task_params)
    redirect_to @task
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<div class="header">
  <div class="tasks-index-icon">
    <%= link_to tasks_path do %>
      <i class="fas fa-bars"></i>
    <% end %>
  </div>
  <h5 class="">MY TASKS</h5>

  <%= link_to new_task_path do  %>
    <div class="new-task-icon">
      <i class="fas fa-plus"></i>
    </div>
  <% end %>
</div>

<div class="search">
  <input type="text" id="search-bar" placeholder="Search from list" />
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManagerReboot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="main-container shadow-lg">
      <%= render "layouts/header" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="edit-task">
  <div class="edit-task-title">
    <h5>Edit task</h5>
  </div>

  <div class="edit-task-form">
    <%= simple_form_for @task do |f| %>
      <%= f.input :title %>
      <%= f.input :details %>
      <%= f.input :completed, as: :boolean %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="tasks-box">
  <div class="tasks">
    <% @tasks.each do |task| %>
      <div class="task">
        <%= link_to task_path(task) do %>
          <div class="task-link">
            <% if task.completed %>
              <i class="fas fa-check task-completed"></i>
            <% else %>
              <i class="far fa-circle"></i>
            <% end %>
            <p><%= task.title %></p>
          </div>
        <% end %>

        <%= link_to task_path(task),
                    method: :delete,
                    data: { confirm: "Are you sure?" } do %>
          <i class="fas fa-trash-alt"></i>
          <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="new-task">
  <div class="new-task-title">
    <h5>New task</h5>
  </div>

  <div class="new-task-form">
    <%= simple_form_for @task do |f| %>
      <%= f.input :title %>
      <%= f.input :details %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="task-show">
  <div class="task-title">
    <h5><%= @task.title %></h5>
  </div>

  <div class="task-details">
    <p><%= @task.details %></p>

    <% if @task.completed %>
      <div class="alert alert-success mt-4" role="alert">
        Task completed
      </div>
    <% end %>
  </div>

  <div class="task-buttons">
    <%= link_to 'Edit', edit_task_path(@task), class: "btn btn-primary" %>
    <%= link_to 'Delete', task_path(@task),
                          method: :delete,
                          data: { confirm: 'Are you sure?'},
                          class: "btn btn-danger" %>
  </div>
</div>